window.BROOKE_SUPABASE_URL = "https://YOUR_PROJECT_REF.supabase.co";
window.BROOKE_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_OR_PUBLISHABLE_KEY";
window.BROOKE_GOOGLE_BOOKS_API_KEY = "YOUR_GOOGLE_BOOKS_API_KEY";
window.BROOKE_SUPABASE_FUNCTIONS_URL = "https://YOUR_PROJECT_REF.supabase.co/functions/v1";
